name: Build and test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v1
      - name: Setting java version to 12
        uses: actions/setup-java@v1
        with:
          java-version: '12'
          architecture: x64

      - name: Build and test
        run: |
          ./gradlew clean test
        env:
          TZ: Europe/Oslo
